EXP:
  seed: 123
  env_name: 'GatheringNewtonian-v0'
SOLVER:
  n_iters: 500
  init_range: 
    v: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
    p: ((0.05, 0.7, 0.05), (0.95, 0.9, 0.95))
  optim:
    type: 'Adam'
    lr: 1e-4
    beta_1: 0.9
    beta_2: 0.99
